MAIN_THEMES_TAXONOMY = {
    "Digital Transformation & Strategy": [
        {"label": "Digital Agenda", "description": "Plans and policies for national or sectoral digital transformation."},
        {"label": "Digital Acceleration", "description": "Initiatives to accelerate the adoption of digital technologies."},
        {"label": "Digital Platforms", "description": "Development and governance of digital service platforms."},
        {"label": "Digital Decade", "description": "Long-term strategic digital transformation objectives spanning a decade."},
        {"label": "Digital Infrastructure", "description": "Physical and virtual systems that support digital operations."},
        {"label": "Digital Trade", "description": "Commerce conducted via digital channels and platforms."},
        {"label": "Digital Policy", "description": "Frameworks and regulations governing digital activities."},
        {"label": "Digital Ecosystem", "description": "Interconnected network of digital services, platforms and stakeholders."},
        {"label": "Digital Investment", "description": "Financial resources allocated to digital transformation projects."},
        {"label": "Digital Regulation", "description": "Rules and standards governing digital activities and services."},
        {"label": "Digital Transitions", "description": "Processes of moving from analog to digital systems."},
        {"label": "Digital Research", "description": "Investigation and development of digital technologies and applications."},
        {"label": "Digital Sustainability", "description": "Environmentally sustainable approaches to digital transformation."},
        {"label": "Digital Economy", "description": "Economic activity derived from digital goods and services."},
        {"label": "Digital Skills Development", "description": "Training and education programs to enhance digital competencies."},
    ],
    "Technology & Innovation": [
        {"label": "Artificial Intelligence", "description": "Development and application of AI systems and machine learning."},
        {"label": "AI Ethics", "description": "Ethical frameworks and considerations in AI development and use."},
        {"label": "Tech-Driven Solutions", "description": "Problem-solving approaches based on technological innovation."},
        {"label": "Quantum Technologies", "description": "Advanced computing technologies based on quantum physics principles."},
        {"label": "ICT Innovation", "description": "Novel approaches in information and communication technologies."},
        {"label": "Technology Regulations", "description": "Legal frameworks governing technological development and use."},
        {"label": "High-Performance Computing", "description": "Advanced computing systems with superior processing capabilities."},
        {"label": "Sustainable Tech", "description": "Technologies designed with environmental sustainability in mind."},
        {"label": "Cloud Computing", "description": "Delivery of computing services over the internet."},
        {"label": "Innovation in Computing", "description": "Novel approaches and breakthroughs in computing technologies."},
        {"label": "Blockchain", "description": "Distributed ledger technology for secure transactions."},
        {"label": "5G", "description": "Fifth generation mobile network technology."},
        {"label": "VRE", "description": "Virtual Research Environments for scientific collaboration."},
    ],
    "Data & Governance": [
        {"label": "Data Governance", "description": "Management of availability, usability and security of data."},
        {"label": "Digital Rights", "description": "Human rights in the context of digital technologies and internet."},
        {"label": "Digital Governance", "description": "Frameworks for managing digital assets and operations."},
        {"label": "Data Protection", "description": "Safeguarding personal data from unauthorized access or use."},
        {"label": "Cybersecurity", "description": "Protection of systems, networks and data from digital attacks."},
        {"label": "Cyber Risk Management", "description": "Identification and mitigation of risks in digital environments."},
        {"label": "Data Privacy", "description": "Policies ensuring proper handling of personal information."},
        {"label": "Digital Access", "description": "Ability to connect to and use digital technologies and services."},
        {"label": "Digital Identity Management", "description": "Systems for verifying and managing online identities."},
        {"label": "Internet Governance", "description": "Development and application of principles governing internet use."},
        {"label": "Digital Ethics", "description": "Moral principles guiding behavior in digital environments."},
        {"label": "E-Governance", "description": "Use of technology to facilitate government services and operations."},
    ],
    "Inclusion & Social Development": [
        {"label": "Digital Inclusion", "description": "Ensuring all individuals have access to digital technologies."},
        {"label": "Social Cohesion", "description": "Building unity among communities through digital means."},
        {"label": "Gender Equality in Tech", "description": "Promoting equal opportunities for all genders in technology."},
        {"label": "Digital Education", "description": "Teaching and learning through digital technologies."},
        {"label": "Connectivity", "description": "Access to internet and digital communication networks."},
        {"label": "Sustainable Digital Development", "description": "Digital growth that meets present needs without compromising future resources."},
    ],
    "Regional & International Cooperation": [
        {"label": "EU-LAC Digital Alliance", "description": "Cooperation between EU and Latin America on digital matters."},
        {"label": "Bi-regional Cooperation", "description": "Collaboration between two regions on technological development."},
        {"label": "Global Digital Cooperation", "description": "Worldwide collaboration on digital governance and technologies."},
        {"label": "Multilateralism", "description": "International cooperation among multiple countries on digital issues."},
        {"label": "EU-CELAC Digital Partnership", "description": "Strategic digital alliance between EU and CELAC countries."},
        {"label": "Digital & Technological Partnerships", "description": "Formal collaborations focused on digital and tech advancement."},
    ],
    }

ACTORS_TAXONOMY = {
    "Political Actors": [
        {"label": "Governments", "description": "National administrative bodies and authorities."},
        {"label": "Government Officials", "description": "Individuals holding positions in government administrations."},
        {"label": "Policy Level Representatives", "description": "Officials involved in policy creation and implementation."},
        {"label": "Community of Latin American and Caribbean States", "description": "Regional bloc of Latin American and Caribbean nations."},
        {"label": "Southern Common Market", "description": "South American trade bloc (Mercosur)."},
        {"label": "Pacific Alliance", "description": "Regional integration initiative involving Latin American countries."},
        {"label": "European Union", "description": "Political and economic union of European member states."},
        {"label": "EU Member States", "description": "Countries belonging to the European Union."},
        {"label": "European Council", "description": "EU institution defining political direction and priorities."},
        {"label": "European Parliament", "description": "Directly elected legislative body of the European Union."},
        {"label": "European Commission", "description": "Executive branch of the European Union."},
        {"label": "EU Delegations", "description": "Diplomatic missions representing the EU abroad."},
        {"label": "Ibero-American General Secretariat", "description": "Organization supporting cooperation among Ibero-American countries."},
        {"label": "Community of Portuguese Language Countries", "description": "Intergovernmental organization of Portuguese-speaking nations."},
        {"label": "International and Ibero-American Foundation for Administration and Public Policies", "description": "Organization promoting governance and public policy development."},
        {"label": "Information and Communication Technologies and Digital Dialogue Leaders", "description": "Key figures leading digital policy discussions."},
        {"label": "Organisation of Ibero-American States", "description": "Intergovernmental organization promoting cooperation in education, science and culture."},
        {"label": "United Nations", "description": "International organization promoting global cooperation."},
        {"label": "United Nations Officials", "description": "Representatives and employees of the United Nations."},
    ],
    "Research and Innovation Actors": [
        {"label": "EU-LAC Foundation", "description": "Organization fostering EU-LAC relations and mutual knowledge."},
        {"label": "Research Software Alliance", "description": "Coalition promoting quality research software."},
        {"label": "Latin American Cooperation of Advanced Networks", "description": "Organization coordinating research networks in Latin America."},
        {"label": "Universities", "description": "Higher education and research institutions."},
        {"label": "Technology Organisations", "description": "Entities focused on technological development and application."},
        {"label": "Research Performing Organisations", "description": "Institutions conducting scientific and technological research."},
        {"label": "Academic Institutions", "description": "Educational bodies involved in research and higher learning."},
        {"label": "Knowledge and Innovation Communities", "description": "Networks bringing together education, research and business."},
        {"label": "European Institute of Innovation and Technology", "description": "EU body promoting innovation and entrepreneurship."},
        {"label": "Digital Innovation Hubs", "description": "Centers supporting digital transformation of businesses."},
        {"label": "Thematic communities", "description": "Groups focused on specific research or innovation topics."},
        {"label": "Researchers", "description": "Individuals conducting scientific investigation."},
        {"label": "Innovators", "description": "People developing new ideas, products or methods."},
        {"label": "Digital for Development Hub", "description": "Platform promoting digital solutions for development challenges."},
        {"label": "EU-LAC Digital Alliance", "description": "Partnership promoting digital cooperation between regions."},
        {"label": "Pan-European Research and Education Network", "description": "Infrastructure connecting European research and education institutions."},
        {"label": "LAC Space Agencies", "description": "Organizations in Latin America focused on space technology and exploration."},
        {"label": "National Research and Education Networks", "description": "Specialized internet service providers for research communities."},
        {"label": "Latin American and Caribbean Network Information Centre", "description": "Regional internet registry for Latin America and the Caribbean."},
        {"label": "Spanish Agency for International Development", "description": "Organization managing Spanish cooperation for development."},
    ],
    "Economic Actors": [
        {"label": "Bilateral Projects", "description": "Collaborative initiatives between two countries."},
        {"label": "Organisation for Economic Cooperation and Development", "description": "International organization promoting economic progress."},
        {"label": "Private Sector Representatives", "description": "Individuals representing business and commercial interests."},
        {"label": "Industry Actors", "description": "Organizations and individuals from specific business sectors."},
        {"label": "Private Sector Intermediaries", "description": "Entities facilitating connections between businesses."},
        {"label": "Inter-American Development Bank", "description": "Financial institution supporting development in Latin America."},
        {"label": "Development Bank of Latin America and the Caribbean", "description": "Multilateral bank promoting sustainable development in the region."},
        {"label": "Central American Bank for Economic Integration", "description": "Financial institution promoting economic integration in Central America."},
        {"label": "World Bank", "description": "International financial institution providing loans and assistance to developing countries."},
        {"label": "Secretariat for Central American Economic Integration", "description": "Organization promoting economic integration in Central America."},
        {"label": "Research Funding Organisations", "description": "Entities providing financial support for research activities."},
        {"label": "Digital Companies", "description": "Businesses focused on digital products and services."},
        {"label": "ICT Companies", "description": "Enterprises specializing in information and communication technologies."},
        {"label": "Telecommunication Companies", "description": "Organizations providing communication services and infrastructure."},
    ],
    "Civil Society Actors": [
        {"label": "Non-governmental Institutions", "description": "Organizations independent from government involvement."},
        {"label": "Civil Society Organisations", "description": "Non-profit groups addressing social or political issues."},
        {"label": "European Digital Rights", "description": "Organization defending rights and freedoms in the digital environment."},
        {"label": "Digital Training and Education Providers", "description": "Entities offering education in digital skills and competencies."},
        {"label": "Digital Transformation Consultants", "description": "Experts advising on digital change processes."},
        {"label": "Digital Skills Development Platforms", "description": "Online services for learning digital abilities."},
        {"label": "Digital Cooperation Organization", "description": "Entity promoting collaboration on digital governance."},
        {"label": "Digital Literacy Initiatives", "description": "Programs promoting basic digital knowledge and skills."},
        {"label": "Technology Providers", "description": "Companies supplying technological products and services."},
    ],
}
