MAIN_THEMES_TAXONOMY = {
    "Digital Transformation & Strategy": [
        {"label": "Digital Agenda", "description": "Plans and policies for national or sectoral digital transformation."},
        {"label": "Digital Acceleration", "description": "Initiatives to accelerate the adoption of digital technologies."},
        {"label": "Digital Platforms", "description": "Development and governance of digital service platforms."},
        {"label": "Digital Decade", "description": "Long-term strategic digital transformation objectives spanning a decade."},
        {"label": "Digital Infrastructure", "description": "Physical and virtual systems that support digital operations."},
        {"label": "Digital Trade", "description": "Commerce conducted via digital channels and platforms."},
        {"label": "Digital Policy", "description": "Frameworks and regulations governing digital activities."},
        {"label": "Digital Ecosystem", "description": "Interconnected network of digital services, platforms and stakeholders."},
        {"label": "Digital Investment", "description": "Financial resources allocated to digital transformation projects."},
        {"label": "Digital Regulation", "description": "Rules and standards governing digital activities and services."},
        {"label": "Digital Transitions", "description": "Processes of moving from analog to digital systems."},
        {"label": "Digital Research", "description": "Investigation and development of digital technologies and applications."},
        {"label": "Digital Sustainability", "description": "Environmentally sustainable approaches to digital transformation."},
        {"label": "Digital Economy", "description": "Economic activity derived from digital goods and services."},
        {"label": "Digital Skills Development", "description": "Training and education programs to enhance digital competencies."},
    ],
    "Technology & Innovation": [
        {"label": "Artificial Intelligence", "description": "Development and application of AI systems and machine learning."},
        {"label": "AI Ethics", "description": "Ethical frameworks and considerations in AI development and use."},
        {"label": "Tech-Driven Solutions", "description": "Problem-solving approaches based on technological innovation."},
        {"label": "Quantum Technologies", "description": "Advanced computing technologies based on quantum physics principles."},
        {"label": "ICT Innovation", "description": "Novel approaches in information and communication technologies."},
        {"label": "Technology Regulations", "description": "Legal frameworks governing technological development and use."},
        {"label": "High-Performance Computing", "description": "Advanced computing systems with superior processing capabilities."},
        {"label": "Sustainable Tech", "description": "Technologies designed with environmental sustainability in mind."},
        {"label": "Cloud Computing", "description": "Delivery of computing services over the internet."},
        {"label": "Innovation in Computing", "description": "Novel approaches and breakthroughs in computing technologies."},
        {"label": "Blockchain", "description": "Distributed ledger technology for secure transactions."},
        {"label": "5G", "description": "Fifth generation mobile network technology."},
        {"label": "VRE", "description": "Virtual Research Environments for scientific collaboration."},
    ],
    "Data & Governance": [
        {"label": "Data Governance", "description": "Management of availability, usability and security of data."},
        {"label": "Digital Rights", "description": "Human rights in the context of digital technologies and internet."},
        {"label": "Digital Governance", "description": "Frameworks for managing digital assets and operations."},
        {"label": "Data Protection", "description": "Safeguarding personal data from unauthorized access or use."},
        {"label": "Cybersecurity", "description": "Protection of systems, networks and data from digital attacks."},
        {"label": "Cyber Risk Management", "description": "Identification and mitigation of risks in digital environments."},
        {"label": "Data Privacy", "description": "Policies ensuring proper handling of personal information."},
        {"label": "Digital Access", "description": "Ability to connect to and use digital technologies and services."},
        {"label": "Digital Identity Management", "description": "Systems for verifying and managing online identities."},
        {"label": "Internet Governance", "description": "Development and application of principles governing internet use."},
        {"label": "Digital Ethics", "description": "Moral principles guiding behavior in digital environments."},
        {"label": "E-Governance", "description": "Use of technology to facilitate government services and operations."},
    ],
    "Inclusion & Social Development": [
        {"label": "Digital Inclusion", "description": "Ensuring all individuals have access to digital technologies."},
        {"label": "Social Cohesion", "description": "Building unity among communities through digital means."},
        {"label": "Gender Equality in Tech", "description": "Promoting equal opportunities for all genders in technology."},
        {"label": "Digital Education", "description": "Teaching and learning through digital technologies."},
        {"label": "Connectivity", "description": "Access to internet and digital communication networks."},
        {"label": "Sustainable Digital Development", "description": "Digital growth that meets present needs without compromising future resources."},
    ],
    "Regional & International Cooperation": [
        {"label": "EU-LAC Digital Alliance", "description": "Cooperation between EU and Latin America on digital matters."},
        {"label": "Bi-regional Cooperation", "description": "Collaboration between two regions on technological development."},
        {"label": "Global Digital Cooperation", "description": "Worldwide collaboration on digital governance and technologies."},
        {"label": "Multilateralism", "description": "International cooperation among multiple countries on digital issues."},
        {"label": "EU-CELAC Digital Partnership", "description": "Strategic digital alliance between EU and CELAC countries."},
        {"label": "Digital & Technological Partnerships", "description": "Formal collaborations focused on digital and tech advancement."},
    ],
    }

ACTORS_TAXONOMY = {
    "Political Actors": [
        {"label": "Governments", "description": "National administrative bodies and authorities."},
        {"label": "Government Officials", "description": "Individuals holding positions in government administrations."},
        {"label": "Policy Level Representatives", "description": "Officials involved in policy creation and implementation."},
        {"label": "Community of Latin American and Caribbean States", "description": "Regional bloc of Latin American and Caribbean nations."},
        {"label": "Southern Common Market", "description": "South American trade bloc (Mercosur)."},
        {"label": "Pacific Alliance", "description": "Regional integration initiative involving Latin American countries."},
        {"label": "European Union", "description": "Political and economic union of European member states."},
        {"label": "EU Member States", "description": "Countries belonging to the European Union."},
        {"label": "European Council", "description": "EU institution defining political direction and priorities."},
        {"label": "European Parliament", "description": "Directly elected legislative body of the European Union."},
        {"label": "European Commission", "description": "Executive branch of the European Union."},
        {"label": "EU Delegations", "description": "Diplomatic missions representing the EU abroad."},
        {"label": "Ibero-American General Secretariat", "description": "Organization supporting cooperation among Ibero-American countries."},
        {"label": "Community of Portuguese Language Countries", "description": "Intergovernmental organization of Portuguese-speaking nations."},
        {"label": "International and Ibero-American Foundation for Administration and Public Policies", "description": "Organization promoting governance and public policy development."},
        {"label": "Information and Communication Technologies and Digital Dialogue Leaders", "description": "Key figures leading digital policy discussions."},
        {"label": "Organisation of Ibero-American States", "description": "Intergovernmental organization promoting cooperation in education, science and culture."},
        {"label": "United Nations", "description": "International organization promoting global cooperation."},
        {"label": "United Nations Officials", "description": "Representatives and employees of the United Nations."},
    ],
    "Research and Innovation Actors": [
        {"label": "EU-LAC Foundation", "description": "Organization fostering EU-LAC relations and mutual knowledge."},
        {"label": "Research Software Alliance", "description": "Coalition promoting quality research software."},
        {"label": "Latin American Cooperation of Advanced Networks", "description": "Organization coordinating research networks in Latin America."},
        {"label": "Universities", "description": "Higher education and research institutions."},
        {"label": "Technology Organisations", "description": "Entities focused on technological development and application."},
        {"label": "Research Performing Organisations", "description": "Institutions conducting scientific and technological research."},
        {"label": "Academic Institutions", "description": "Educational bodies involved in research and higher learning."},
        {"label": "Knowledge and Innovation Communities", "description": "Networks bringing together education, research and business."},
        {"label": "European Institute of Innovation and Technology", "description": "EU body promoting innovation and entrepreneurship."},
        {"label": "Digital Innovation Hubs", "description": "Centers supporting digital transformation of businesses."},
        {"label": "Thematic communities", "description": "Groups focused on specific research or innovation topics."},
        {"label": "Researchers", "description": "Individuals conducting scientific investigation."},
        {"label": "Innovators", "description": "People developing new ideas, products or methods."},
        {"label": "Digital for Development Hub", "description": "Platform promoting digital solutions for development challenges."},
        {"label": "EU-LAC Digital Alliance", "description": "Partnership promoting digital cooperation between regions."},
        {"label": "Pan-European Research and Education Network", "description": "Infrastructure connecting European research and education institutions."},
        {"label": "LAC Space Agencies", "description": "Organizations in Latin America focused on space technology and exploration."},
        {"label": "National Research and Education Networks", "description": "Specialized internet service providers for research communities."},
        {"label": "Latin American and Caribbean Network Information Centre", "description": "Regional internet registry for Latin America and the Caribbean."},
        {"label": "Spanish Agency for International Development", "description": "Organization managing Spanish cooperation for development."},
    ],
    "Economic Actors": [
        {"label": "Bilateral Projects", "description": "Collaborative initiatives between two countries."},
        {"label": "Organisation for Economic Cooperation and Development", "description": "International organization promoting economic progress."},
        {"label": "Private Sector Representatives", "description": "Individuals representing business and commercial interests."},
        {"label": "Industry Actors", "description": "Organizations and individuals from specific business sectors."},
        {"label": "Private Sector Intermediaries", "description": "Entities facilitating connections between businesses."},
        {"label": "Inter-American Development Bank", "description": "Financial institution supporting development in Latin America."},
        {"label": "Development Bank of Latin America and the Caribbean", "description": "Multilateral bank promoting sustainable development in the region."},
        {"label": "Central American Bank for Economic Integration", "description": "Financial institution promoting economic integration in Central America."},
        {"label": "World Bank", "description": "International financial institution providing loans and assistance to developing countries."},
        {"label": "Secretariat for Central American Economic Integration", "description": "Organization promoting economic integration in Central America."},
        {"label": "Research Funding Organisations", "description": "Entities providing financial support for research activities."},
        {"label": "Digital Companies", "description": "Businesses focused on digital products and services."},
        {"label": "ICT Companies", "description": "Enterprises specializing in information and communication technologies."},
        {"label": "Telecommunication Companies", "description": "Organizations providing communication services and infrastructure."},
    ],
    "Civil Society Actors": [
        {"label": "Non-governmental Institutions", "description": "Organizations independent from government involvement."},
        {"label": "Civil Society Organisations", "description": "Non-profit groups addressing social or political issues."},
        {"label": "European Digital Rights", "description": "Organization defending rights and freedoms in the digital environment."},
        {"label": "Digital Training and Education Providers", "description": "Entities offering education in digital skills and competencies."},
        {"label": "Digital Transformation Consultants", "description": "Experts advising on digital change processes."},
        {"label": "Digital Skills Development Platforms", "description": "Online services for learning digital abilities."},
        {"label": "Digital Cooperation Organization", "description": "Entity promoting collaboration on digital governance."},
        {"label": "Digital Literacy Initiatives", "description": "Programs promoting basic digital knowledge and skills."},
        {"label": "Technology Providers", "description": "Companies supplying technological products and services."},
    ],
}

BENEFICIARIES_TAXONOMY = {
    "SMEs / Businesses": [
        {"label": "Small and Medium Enterprises", "description": "Companies with fewer than 250 employees."},
        {"label": "Entrepreneurs", "description": "Individuals who create or operate businesses."},
        {"label": "Companies", "description": "Commercial business organizations."},
        {"label": "Private Sector Organizations", "description": "Businesses owned by private individuals or groups."},
        {"label": "Business Associations", "description": "Groups representing business interests."},
    ],
    "Start-ups / Innovators": [
        {"label": "Start-ups", "description": "Newly established businesses focused on innovation."},
        {"label": "Scale-ups", "description": "Growing start-ups expanding their operations."},
        {"label": "Tech Hubs", "description": "Centers fostering technological innovation and entrepreneurship."},
        {"label": "Incubators", "description": "Organizations supporting early-stage business development."},
        {"label": "Digital Innovators", "description": "Individuals or groups creating novel digital solutions."},
    ],
    "Large Corporations": [
        {"label": "Telecommunication Companies", "description": "Organizations providing communication services."},
        {"label": "Multinational Corporations", "description": "Companies operating in multiple countries."},
        {"label": "Tech Giants", "description": "Large influential technology companies."},
        {"label": "Industry Leaders", "description": "Major companies that dominate specific sectors."},
    ],
    "Researchers & Academia": [
        {"label": "Researchers", "description": "Individuals conducting scholarly or scientific investigations."},
        {"label": "Universities", "description": "Higher education institutions involved in research."},
        {"label": "Research and Development Centers", "description": "Organizations dedicated to research and innovation."},
        {"label": "Academic Institutions", "description": "Educational establishments involved in higher learning."},
        {"label": "Scientific Community", "description": "Network of professionals in scientific fields."},
    ],
    "Students & Youth": [
        {"label": "Youth", "description": "Young people, typically between ages 15-24."},
        {"label": "Students", "description": "Individuals engaged in formal education."},
        {"label": "Young Professionals", "description": "Early-career workers typically under 30."},
        {"label": "Digital Natives", "description": "Individuals who grew up with digital technology."},
        {"label": "Youth Organizations", "description": "Groups representing young people's interests."},
        {"label": "Children", "description": "Individuals under 18 years old."},
    ],
    "Migrants & Refugees": [
        {"label": "Migrants", "description": "People who have moved to a different country or region."},
        {"label": "Refugees", "description": "Individuals forced to flee their country due to conflict, persecution or disaster."}
    ],
    "Women & Girls": [
        {"label": "Women in Tech", "description": "Females working in or studying technology fields."},
        {"label": "Gender Equality Initiatives", "description": "Programs promoting equal opportunities across genders."},
        {"label": "Female Entrepreneurs", "description": "Women who start or operate businesses."},
        {"label": "Women's Networks", "description": "Professional groups supporting women in various sectors."},
    ],
    "Rural & Remote Communities": [
        {"label": "Rural Populations", "description": "People living in non-urban areas."},
        {"label": "Remote Area Citizens", "description": "Individuals in isolated geographical locations."},
        {"label": "Rural Cooperatives", "description": "Collaborative organizations in rural settings."},
        {"label": "Underserved Communities", "description": "Groups with limited access to resources and services."},
    ],
    "Indigenous Peoples & Ethnic Groups": [
        {"label": "Indigenous Communities", "description": "Original inhabitants of a region."},
        {"label": "Afro-descendant Groups", "description": "People of African ancestry."},
        {"label": "Minority Groups", "description": "Ethnically or culturally distinct groups."},
        {"label": "Traditional Communities", "description": "Groups maintaining traditional cultural practices."},
    ],
    "Persons with Disabilities": [
        {"label": "Persons with Disabilities", "description": "Individuals with physical, mental, or sensory impairments."},
        {"label": "Accessibility Beneficiaries", "description": "People who benefit from accessible design and services."},
        {"label": "Inclusive Technology Users", "description": "Users of technology designed for accessibility."},
    ],
    "General Citizens / Consumers": [
        {"label": "Citizens", "description": "Members of the general public."},
        {"label": "Consumers", "description": "People who purchase goods and services."},
        {"label": "Digital Users", "description": "Individuals using digital products and services."},
        {"label": "General Public", "description": "The broader population."},
    ],
    "Public Sector / Governments": [
        {"label": "Ministries", "description": "Government departments headed by ministers."},
        {"label": "Local Authorities", "description": "Governmental bodies at local or regional level."},
        {"label": "Public Institutions", "description": "Organizations funded or controlled by government."},
        {"label": "Public Servants", "description": "Employees of government or public institutions."},
    ],
    "Civil Society / NGOs": [
        {"label": "Civil Society Organizations", "description": "Non-governmental, non-profit entities."},
        {"label": "NGOs", "description": "Non-governmental organizations addressing social issues."},
        {"label": "Advocacy Groups", "description": "Organizations promoting specific causes or policies."},
        {"label": "Community Organizations", "description": "Local groups addressing community needs."},
    ],
    "Farmers & Primary Producers": [
        {"label": "Farmers", "description": "People who cultivate land and raise crops or livestock."},
        {"label": "Fisheries", "description": "Entities involved in catching, processing, or selling fish."},
        {"label": "Agricultural Cooperatives", "description": "Farmer-owned collective businesses."},
        {"label": "Rural Producers", "description": "Those producing goods in rural areas."},
    ],
    "Health Sector": [
        {"label": "Patients", "description": "Recipients of healthcare services."},
        {"label": "Health Professionals", "description": "Workers in medical and healthcare fields."},
        {"label": "Healthcare Institutions", "description": "Organizations providing medical services."},
        {"label": "Public Health Stakeholders", "description": "Entities involved in population health."},
    ],
    "Investors & Financial Actors": [
        {"label": "Investors", "description": "Individuals or entities that allocate capital for profit."},
        {"label": "Development Banks", "description": "Financial institutions focused on promoting development."},
        {"label": "Venture Capital Firms", "description": "Companies providing funding to early-stage businesses."},
        {"label": "Financial Institutions", "description": "Organizations involved in financial transactions."},
    ],
}

SDG_TAXONOMY = [
    {"label": "SDG 1: No Poverty", "description": "End poverty in all its forms everywhere."},
    {"label": "SDG 2: Zero Hunger", "description": "End hunger, achieve food security and improved nutrition, and promote sustainable agriculture."},
    {"label": "SDG 3: Good Health and Well-being", "description": "Ensure healthy lives and promote well-being for all at all ages."},
    {"label": "SDG 4: Quality Education", "description": "Ensure inclusive and equitable quality education and promote lifelong learning opportunities for all."},
    {"label": "SDG 5: Gender Equality", "description": "Achieve gender equality and empower all women and girls."},
    {"label": "SDG 6: Clean Water and Sanitation", "description": "Ensure availability and sustainable management of water and sanitation for all."},
    {"label": "SDG 7: Affordable and Clean Energy", "description": "Ensure access to affordable, reliable, sustainable and modern energy for all."},
    {"label": "SDG 8: Decent Work and Economic Growth", "description": "Promote sustained, inclusive and sustainable economic growth, full and productive employment and decent work for all."},
    {"label": "SDG 9: Industry, Innovation and Infrastructure", "description": "Build resilient infrastructure, promote inclusive and sustainable industrialization and foster innovation."},
    {"label": "SDG 10: Reduced Inequalities", "description": "Reduce inequality within and among countries."},
    {"label": "SDG 11: Sustainable Cities and Communities", "description": "Make cities and human settlements inclusive, safe, resilient and sustainable."},
    {"label": "SDG 12: Responsible Consumption and Production", "description": "Ensure sustainable consumption and production patterns."},
    {"label": "SDG 13: Climate Action", "description": "Take urgent action to combat climate change and its impacts."},
    {"label": "SDG 14: Life Below Water", "description": "Conserve and sustainably use the oceans, seas and marine resources for sustainable development."},
    {"label": "SDG 15: Life on Land", "description": "Protect, restore and promote sustainable use of terrestrial ecosystems, sustainably manage forests, combat desertification, and halt and reverse land degradation and halt biodiversity loss."},
    {"label": "SDG 16: Peace, Justice and Strong Institutions", "description": "Promote peaceful and inclusive societies for sustainable development, provide access to justice for all and build effective, accountable and inclusive institutions at all levels."},
    {"label": "SDG 17: Partnerships for the Goals", "description": "Strengthen the means of implementation and revitalize the global partnership for sustainable development."},
]
